/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/visualize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Visualize
         * @description Plan an analysis for the question, run it, and return the chart spec.
         *
         *     Takes 10-40 s: the planner model runs first, then trials are fetched at about one page
         *     of 1,000 per second to stay inside ClinicalTrials.gov's rate limit.
         */
        post: operations["visualize_visualize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisSpec
         * @description The agent's plan for answering a question. Code executes it; the model supplies no data.
         */
        AnalysisSpec: {
            /** @description Shared by every series. Must include every filter from the request. */
            filters?: components["schemas"]["Filters"];
            /**
             * Compare
             * @description Two to four cohorts to compare side by side; empty for no comparison.
             */
            compare?: components["schemas"]["Series"][];
            /**
             * Dimensions
             * @description Temporal: start_year. Quantitative: duration_months, enrollment. Entities: condition, country, drug, lead_sponsor. All others are categorical.
             */
            dimensions: components["schemas"]["Dimension"][];
            /** @description Must fit the dimensions. bar: one categorical dimension. grouped_bar: one categorical dimension plus a comparison or a second categorical dimension. time_series: start_year first, optionally a categorical dimension or a comparison as the series. histogram: one quantitative dimension. scatter: two different quantitative dimensions, one point per trial. network: one entity dimension (co-occurrence within a trial, e.g. drug-drug) or two different entity dimensions (bipartite, e.g. sponsor-drug). */
            chart: components["schemas"]["ChartType"];
            /**
             * Top N
             * @description Keep only the N largest categories, or the N best-connected network nodes.
             */
            top_n?: number | null;
            /**
             * Title
             * @description What the chart shows. Do not state counts or results.
             */
            title: string;
            /**
             * Assumptions
             * @description Interpretation choices a reader should know, e.g. 'start year, not completion year'.
             */
            assumptions?: string[];
        };
        /**
         * Channel
         * @description Maps a data field to a visual channel, in the style of Vega-Lite.
         */
        Channel: {
            /** Field */
            field: string;
            /**
             * Type
             * @enum {string}
             */
            type: "nominal" | "ordinal" | "quantitative" | "temporal";
            /** Title */
            title: string;
            /**
             * Sort
             * @description Explicit category order for ordinal fields, e.g. phases.
             */
            sort?: string[] | null;
        };
        /**
         * ChartType
         * @enum {string}
         */
        ChartType: "bar" | "grouped_bar" | "time_series" | "histogram" | "scatter" | "network";
        /**
         * ChartVisualization
         * @description Bar, grouped bar, time series, histogram or scatter.
         *
         *     `data` is a flat list of records; `encoding` names the keys to plot. Besides those keys,
         *     every record carries:
         *     - `nct_ids`: the trials counted in the record (one trial for scatter points); when
         *       `meta.counts.method` is `server_counts` this is a sample and `trial_count` is the total,
         *     - `citations`: the field values that put up to three of those trials there.
         *     Time series records may also carry `partial_period: true` (the year is not over) or
         *     `projected: true` (the year is in the future, so its trials have planned start dates).
         */
        ChartVisualization: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bar" | "grouped_bar" | "histogram" | "scatter" | "time_series";
            /** Title */
            title: string;
            encoding: components["schemas"]["XYEncoding"];
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Citation
         * @description One API field value that puts a trial into a datum.
         */
        Citation: {
            /**
             * Nct Id
             * @example NCT01876511
             */
            nct_id: string;
            /**
             * Field
             * @description Path in the ClinicalTrials.gov study record.
             * @example protocolSection.armsInterventionsModule.interventions[0].name
             */
            field: string;
            /**
             * Value
             * @description Exact value at that path.
             * @example MK-3475
             */
            value: string;
        };
        /**
         * Counts
         * @description How the numbers were obtained, and what was left out.
         *
         *     - fetched_records: trials were downloaded and counted here; fetched = plotted +
         *       sum(excluded counts). With a comparison, a trial in two series counts once in each.
         *     - server_counts: ClinicalTrials.gov counted each value directly (used for large result sets
         *       or when it needs fewer requests); counts cover every matching trial, and each datum's
         *       nct_ids are a sample.
         */
        Counts: {
            /**
             * Method
             * @default fetched_records
             * @enum {string}
             */
            method: "fetched_records" | "server_counts";
            /**
             * Matched
             * @description Trials the API matched for the filters.
             */
            matched: number;
            /**
             * Fetched
             * @description Trials downloaded; lower than matched when truncated.
             */
            fetched: number;
            /**
             * Plotted
             * @description Trials that appear in the visualization.
             */
            plotted: number;
            /** Excluded */
            excluded?: components["schemas"]["Exclusion"][];
        };
        /**
         * Dimension
         * @description Trial attributes the analysis can group, bin or plot by.
         * @enum {string}
         */
        Dimension: "start_year" | "phase" | "status" | "sponsor_class" | "lead_sponsor" | "intervention_type" | "drug" | "condition" | "country" | "enrollment" | "duration_months";
        /** Exclusion */
        Exclusion: {
            /** Reason */
            reason: string;
            /** Count */
            count: number;
        };
        /**
         * Filters
         * @description Which trials to include. Every field is optional; set fields are ANDed together.
         */
        Filters: {
            /**
             * Drug Name
             * @description Drug or biologic listed as a trial intervention. Synonyms known to ClinicalTrials.gov match too (Keytruda and MK-3475 both match pembrolizumab).
             */
            drug_name?: string | null;
            /**
             * Condition
             * @description Disease or condition studied.
             */
            condition?: string | null;
            /**
             * Sponsor
             * @description Lead or collaborating sponsor.
             */
            sponsor?: string | null;
            /**
             * Country
             * @description Country with at least one trial site.
             */
            country?: string | null;
            /**
             * Phases
             * @description Keep trials in any of these.
             */
            phases?: components["schemas"]["Phase"][];
            /**
             * Statuses
             * @description Keep trials whose overall status is any of these.
             */
            statuses?: components["schemas"]["Status"][];
            /**
             * Start Year
             * @description Earliest trial start year, inclusive.
             */
            start_year?: number | null;
            /**
             * End Year
             * @description Latest trial start year, inclusive.
             */
            end_year?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Meta */
        Meta: {
            /**
             * Source
             * @default ClinicalTrials.gov API v2
             */
            source: string;
            /**
             * Data Timestamp
             * @description When ClinicalTrials.gov last refreshed.
             */
            data_timestamp?: string | null;
            /** @description The plan that was executed. */
            spec?: components["schemas"]["AnalysisSpec"] | null;
            counts?: components["schemas"]["Counts"] | null;
            /**
             * Truncated
             * @description True when only the first trials were fetched.
             * @default false
             */
            truncated: boolean;
            /**
             * Notes
             * @description Data caveats found while building the chart, e.g. estimated start dates.
             */
            notes?: string[];
            /**
             * Models
             * @description Model used for each role, e.g. planner and labeler.
             */
            models?: {
                [key: string]: string;
            };
            /**
             * Usage
             * @description Planner model requests, tool calls and tokens.
             */
            usage?: {
                [key: string]: number;
            };
        };
        /** NetworkData */
        NetworkData: {
            /** Nodes */
            nodes: components["schemas"]["NetworkNode"][];
            /** Edges */
            edges: components["schemas"]["NetworkEdge"][];
        };
        /** NetworkEdge */
        NetworkEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Trial Count
             * @description Distinct trials linking both ends; width by this.
             */
            trial_count: number;
            /** Nct Ids */
            nct_ids: string[];
            /**
             * Citations
             * @description Field values naming both ends, for up to three of the trials.
             */
            citations: components["schemas"]["Citation"][];
        };
        /**
         * NetworkEncoding
         * @description Fixed mapping from node and edge fields to visual channels.
         */
        NetworkEncoding: {
            /**
             * Node Label
             * @default label
             * @constant
             */
            node_label: "label";
            /**
             * Node Size
             * @default trial_count
             * @constant
             */
            node_size: "trial_count";
            /**
             * Node Color
             * @default group
             * @constant
             */
            node_color: "group";
            /**
             * Edge Width
             * @default trial_count
             * @constant
             */
            edge_width: "trial_count";
        };
        /** NetworkNode */
        NetworkNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** @description Entity kind; colour nodes by this. */
            group: components["schemas"]["Dimension"];
            /**
             * Trial Count
             * @description Distinct trials touching this node; size by this.
             */
            trial_count: number;
            /** Nct Ids */
            nct_ids: string[];
        };
        /**
         * NetworkVisualization
         * @description Node-link graph: bipartite when nodes come from two groups, co-occurrence when one.
         */
        NetworkVisualization: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "network";
            /** Title */
            title: string;
            encoding?: components["schemas"]["NetworkEncoding"];
            data: components["schemas"]["NetworkData"];
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "NA" | "EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4";
        /**
         * Series
         * @description One cohort in a comparison, e.g. the trials for one of two drugs.
         */
        Series: {
            /**
             * Label
             * @description Legend label for this cohort.
             */
            label: string;
            /** @description Added on top of the plan's shared filters. */
            filters: components["schemas"]["Filters"];
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE_NOT_RECRUITING" | "COMPLETED" | "ENROLLING_BY_INVITATION" | "NOT_YET_RECRUITING" | "RECRUITING" | "SUSPENDED" | "TERMINATED" | "WITHDRAWN" | "AVAILABLE" | "NO_LONGER_AVAILABLE" | "TEMPORARILY_NOT_AVAILABLE" | "APPROVED_FOR_MARKETING" | "WITHHELD" | "UNKNOWN";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisualizeRequest
         * @description Body of POST /visualize: a question plus optional filters.
         *
         *     Filters given here are hard constraints. The agent may add filters it reads from the
         *     question, but it cannot drop or change these.
         * @example {
         *       "drug_name": "Pembrolizumab",
         *       "query": "How has the number of trials for this drug changed over time?"
         *     }
         * @example {
         *       "query": "Show a network of sponsors and drugs for glioblastoma trials"
         *     }
         */
        VisualizeRequest: {
            /**
             * Drug Name
             * @description Drug or biologic listed as a trial intervention. Synonyms known to ClinicalTrials.gov match too (Keytruda and MK-3475 both match pembrolizumab).
             */
            drug_name?: string | null;
            /**
             * Condition
             * @description Disease or condition studied.
             */
            condition?: string | null;
            /**
             * Sponsor
             * @description Lead or collaborating sponsor.
             */
            sponsor?: string | null;
            /**
             * Country
             * @description Country with at least one trial site.
             */
            country?: string | null;
            /**
             * Phases
             * @description Keep trials in any of these.
             */
            phases?: components["schemas"]["Phase"][];
            /**
             * Statuses
             * @description Keep trials whose overall status is any of these.
             */
            statuses?: components["schemas"]["Status"][];
            /**
             * Start Year
             * @description Earliest trial start year, inclusive.
             */
            start_year?: number | null;
            /**
             * End Year
             * @description Latest trial start year, inclusive.
             */
            end_year?: number | null;
            /**
             * Query
             * @description Natural-language question about clinical trials.
             */
            query: string;
        };
        /**
         * VisualizeResponse
         * @description Body returned by POST /visualize.
         *
         *     `status` decides what is present:
         *     - ok: `visualization` and `meta.spec` are set.
         *     - cannot_answer: `message` says why; `visualization` is null.
         *     - error: `message` describes the failure; `visualization` is null.
         */
        VisualizeResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "cannot_answer" | "error";
            /** Message */
            message?: string | null;
            /** Visualization */
            visualization?: (components["schemas"]["ChartVisualization"] | components["schemas"]["NetworkVisualization"]) | null;
            meta?: components["schemas"]["Meta"];
        };
        /** XYEncoding */
        XYEncoding: {
            x: components["schemas"]["Channel"];
            /** @description Bin end, for histograms. */
            x2?: components["schemas"]["Channel"] | null;
            y: components["schemas"]["Channel"];
            /** @description Series, for grouped bars and multi-line. */
            color?: components["schemas"]["Channel"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    visualize_visualize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
